### ISSUE TITLE
Logo image takes up all the space such that other contents cannot be seen.

### ISSUE THREAD

**Issue by ibraheem-moosa** [OpenBangla/website-old#1]
Currently the logo image takes up all the space of the webpage. Scrolling down does not help since the content is behind the image. This can probably be solved by moving the logo to navigation bar. If you can tell me where to make the changes and how to test the website offline I can probably fix it.

**Comment by mominul** [comment]
Thanks for the issue, but I am not able to reproduce the issue. The logo is auto-hidden when the user scrolls the page. Can you kindly give me a screenshot regarding the issue?

**Comment by ibraheem-moosa** [comment]
Sure. I am using Firefox 60.0.1 in Ubuntu by the way.
When slider is at the top.

![screenshot from 2018-05-30 12-30-41](https://user-images.githubusercontent.com/14109029/40702886-556414c0-6405-11e8-887d-b98b3c672f9e.png)
When slider is at the bottom.

![screenshot from 2018-05-30 12-29-52](https://user-images.githubusercontent.com/14109029/40702890-59183a6a-6405-11e8-9a05-60a7c1571aaf.png)

**Comment by mominul** [comment]
:confused: But here is the website on my end:
![screenshot_19](https://user-images.githubusercontent.com/9459891/40703203-4279587e-6406-11e8-9df8-453ece3b0bb6.png)
I am very confused about how that issue is happening to you...

**Comment by ibraheem-moosa** [comment]
I am seeing the issue in the live website at *http://openbangla.github.io/
<http://openbangla.github.io/>*. Probably you haven't pushed the latest
updates to the live website, right?

**Comment by mominul** [comment]
No, I am also visiting the [live website](http://openbangla.github.io/). Can you try clearing the Firefox cache? https://support.mozilla.org/en-US/kb/how-clear-firefox-cache

**Comment by ibraheem-moosa** [comment]
The issue still persists. I have also tried explicitly disable cache from Network tab of developer tools. It is still same.

**Comment by ibraheem-moosa** [comment]
I think I've found the problem. I was actually using the [https version](https://openbangla.github.io/). Firefox by default blocks unsecured content in https pages. It was blocking some images, scripts and css files.

![screenshot from 2018-05-30 13-22-11](https://user-images.githubusercontent.com/14109029/40705353-8440eece-640c-11e8-890e-d5233c24128c.png)

**Comment by ibraheem-moosa** [comment]
Changing all the http links to https should probably solve the problem. 
[How to fix a website with blocked mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content)

**Comment by mominul** [comment]
Thanks for the detailed response! I can also reproduce the issue by using the https protocol. I think GitHub has an option to enable https encryption. I will have a look into that.

**Comment by mominul** [comment]
I think I have fixed this issue. :tada:  Now the website is successfully served over the HTTPS protocol. Thank you for your detailed information and help.
Sorry for the delay!!
